-- MySQL Script generated by MySQL Workbench
-- Wed May 31 19:48:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patients` (
  `patient_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  PRIMARY KEY (`patient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `Doctor_id` INT NOT NULL,
  `phone_number` INT NULL,
  `specialization` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Doctor_id`),
  UNIQUE INDEX `specialization_UNIQUE` (`specialization` ASC) VISIBLE,
  UNIQUE INDEX `Doctor_id_UNIQUE` (`Doctor_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointment` (
  `date` DATE NOT NULL,
  `time` DATETIME NOT NULL,
  `patient_id` VARCHAR(45) NOT NULL,
  `Patients_patient_id` INT NOT NULL,
  INDEX `fk_Appointment_Patients1_idx` (`Patients_patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Patients1`
    FOREIGN KEY (`Patients_patient_id`)
    REFERENCES `mydb`.`Patients` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prescription` (
  `prescription_id` INT NOT NULL,
  `patient_id` VARCHAR(45) NOT NULL,
  `doctor_id` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `Patients_patient_id` INT NOT NULL,
  `Doctor_Doctor_id` INT NOT NULL,
  PRIMARY KEY (`prescription_id`),
  INDEX `fk_Prescription_Doctor1_idx` (`Doctor_Doctor_id` ASC) VISIBLE,
  INDEX `fk_Prescription_Patients1_idx` (`Doctor_Doctor_id` ASC, `Patients_patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Prescription_Patients1`
    FOREIGN KEY (`Doctor_Doctor_id` , `Patients_patient_id`)
    REFERENCES `mydb`.`Patients` (`patient_id` , `patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Prescription_Doctor1`
    FOREIGN KEY (`Doctor_Doctor_id`)
    REFERENCES `mydb`.`Doctor` (`Doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Test`(
  `test_id` INT NOT NULL,
  `doctor_id` VARCHAR(45) NOT NULL,
  `Doctor_Doctor_id` INT NOT NULL,
  `patient_id` VARCHAR(45) NOT NULL,
  `Patients_patient_id` INT NOT NULL,
  `test_date` DATE NOT NULL,
  `test_result` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`test_id`),
  INDEX `fk_Test_Doctor1_idx` (`Doctor_Doctor_id` ASC, `Patients_patient_id` ASC) VISIBLE,
  INDEX `fk_Test_Patients1_idx` (`Patients_patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Test_Doctor1`
    FOREIGN KEY (`Doctor_Doctor_id` , `Patients_patient_id`)
    REFERENCES `mydb`.`Doctor` (`Doctor_id` , `Doctor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Test_Patients1`
    FOREIGN KEY (`Patients_patient_id`)
    REFERENCES `mydb`.`Patients` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MedicalRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MedicalRecord` (
  `MedicalRecord_id` INT NOT NULL,
  `doctor_id` VARCHAR(45) NOT NULL,
  `Patient_id` VARCHAR(45) NOT NULL,
  `Patients_patient_id` INT NOT NULL,
  `MedicalRecordcol1` VARCHAR(45) NOT NULL,
  `Doctor_Doctor_id` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`MedicalRecord_id`),
  INDEX `fk_MedicalRecord_Patients1_idx` (`Patients_patient_id` ASC) VISIBLE,
  INDEX `fk_MedicalRecord_Doctor1_idx` (`Doctor_Doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_MedicalRecord_Patients1`
    FOREIGN KEY (`Patients_patient_id`)
    REFERENCES `mydb`.`Patients` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_MedicalRecord_Doctor1`
    FOREIGN KEY (`Doctor_Doctor_id`)
    REFERENCES `mydb`.`Doctor` (`Doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `Department_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NULL,
  `doctor_id` VARCHAR(45) NULL,
  `Doctor_Doctor_id` INT NOT NULL,
  PRIMARY KEY (`Department_id`),
  INDEX `fk_Department_Doctor1_idx` (`Doctor_Doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Doctor1`
    FOREIGN KEY (`Doctor_Doctor_id`)
    REFERENCES `mydb`.`Doctor` (`Doctor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admission` (
  `Admission_id` INT NOT NULL,
  `patient_id` VARCHAR(45) NULL,
  `Patients_patient_id` INT NOT NULL,
  `admission_date` DATE NOT NULL,
  `discharge_date` DATE NOT NULL,
  PRIMARY KEY (`Admission_id`),
  INDEX `fk_Admission_Patients1_idx` (`Patients_patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Admission_Patients1`
    FOREIGN KEY (`Patients_patient_id`)
    REFERENCES `mydb`.`Patients` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ward` (
  `wrad_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `department_id` VARCHAR(45) NULL,
  `Department_Department_id` INT NOT NULL,
  PRIMARY KEY (`wrad_id`),
  INDEX `fk_Ward_Department1_idx` (`Department_Department_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ward_Department1`
    FOREIGN KEY (`Department_Department_id`)
    REFERENCES `mydb`.`Department` (`Department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bed` (
  `Bed_id` INT NOT NULL,
  `ward_id` VARCHAR(45) NOT NULL,
  `Ward_wrad_id` INT NOT NULL,
  `bed_number` INT NULL,
  `availability` TINYINT NOT NULL,
  PRIMARY KEY (`Bed_id`),
  INDEX `fk_Bed_Ward1_idx` (`Ward_wrad_id` ASC) VISIBLE,
  CONSTRAINT `fk_Bed_Ward1`
    FOREIGN KEY (`Ward_wrad_id`)
    REFERENCES `mydb`.`Ward` (`wrad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice` (
  `invoice_id` INT NOT NULL,
  `patient_id` VARCHAR(45) NULL,
  `Patients_patient_id` INT NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`invoice_id`),
  INDEX `fk_invoice_Patients1_idx` (`Patients_patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_Patients1`
    FOREIGN KEY (`Patients_patient_id`)
    REFERENCES `mydb`.`Patients` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Insurance` (
  `Insurance_id` INT NOT NULL,
  `patient_id` VARCHAR(45) NOT NULL,
  `police_number` VARCHAR(45) NOT NULL,
  `provider` VARCHAR(45) NOT NULL,
  `Patients_patient_id` INT NOT NULL,
  PRIMARY KEY (`Insurance_id`),
  INDEX `fk_Insurance_Patients1_idx` (`Patients_patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Insurance_Patients1`
    FOREIGN KEY (`Patients_patient_id`)
    REFERENCES `mydb`.`Patients` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


SET SQL_MODE=@OLD_SQL_MODE
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
